use_frameworks!

platform :ios, '10.0'

target 'MMTToolForStringPicker_Example' do
  pod 'MMTToolForStringPicker', :path => '../'

  target 'MMTToolForStringPicker_Tests' do
    inherit! :search_paths

    
  end
end
